replicaCount: 3

image:
  repository: celliott/weather_exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: weather_exporter
  type: ClusterIP
  externalPort: 9265
  internalPort: 9265

resources: {}
